# Generated by Django 5.2.3 on 2025-08-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_nominal', models.PositiveIntegerField(help_text='Capacidade nominal em unidades por hora')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('quantidade_produzida', models.PositiveIntegerField()),
                ('quantidade_defeituosa', models.PositiveIntegerField(default=0)),
                ('tempo_parado', models.PositiveIntegerField(default=0, help_text='Tempo parado em minutos')),
                ('motivo_parada', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sgpi.linhaproducao')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
