# Generated by Django 5.2.3 on 2025-08-17 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproducao',
            name='operador',
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='turno',
            field=models.CharField(choices=[('1/especial', '1/Especial'), ('2/especial', '2/Especial'), ('3/especial', '3/Especial')], max_length=10),
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='sgpi.registroproducao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('quantidade_produzida', models.PositiveIntegerField()),
                ('quantidade_defeituosa', models.PositiveIntegerField(default=0)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_hora', to='sgpi.registroproducao')),
            ],
        ),
    ]
