# Generated by Django 5.2.3 on 2025-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0002_remove_registroproducao_operador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproducao',
            name='motivo_parada',
        ),
        migrations.AlterField(
            model_name='registrohora',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
