# Generated by Django 5.2.3 on 2025-08-17 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0003_remove_registroproducao_motivo_parada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parada',
            options={'ordering': ('hora_inicio',), 'verbose_name': 'Parada', 'verbose_name_plural': 'Paradas'},
        ),
        migrations.AlterModelOptions(
            name='registrohora',
            options={'ordering': ('hora_inicio',), 'verbose_name': 'Registro por intervalo', 'verbose_name_plural': 'Registro horas'},
        ),
        migrations.AlterModelOptions(
            name='registroproducao',
            options={'verbose_name': 'Registro de produção', 'verbose_name_plural': 'Registro producaos'},
        ),
        migrations.RenameField(
            model_name='registrohora',
            old_name='hora',
            new_name='hora_fim',
        ),
        migrations.AddField(
            model_name='registrohora',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='motivo_parada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='duracao',
            field=models.PositiveIntegerField(default=0, help_text='Duração em minutos (calculada automaticamente)'),
        ),
        migrations.AlterUniqueTogether(
            name='registroproducao',
            unique_together={('linha', 'data', 'turno')},
        ),
    ]
