# Generated by Django 5.2.3 on 2025-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0004_alter_parada_options_alter_registrohora_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohora',
            options={'ordering': ('hora_inicio',)},
        ),
        migrations.RemoveField(
            model_name='registroproducao',
            name='motivo_parada',
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='finalizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
