# Generated by Django 5.2.6 on 2025-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0005_alter_registrohora_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroproducao',
            options={'verbose_name': 'Registro de produção', 'verbose_name_plural': 'Registros de producão'},
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='motivo_parada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
