# Generated by Django 5.2.3 on 2025-09-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0006_alter_registroproducao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroproducao',
            options={'verbose_name': 'Registro de produção', 'verbose_name_plural': 'Registros de produção'},
        ),
        migrations.AlterUniqueTogether(
            name='registroproducao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='turno',
            field=models.CharField(choices=[('1/especial', '1/Especial'), ('2/especial', '2/Especial'), ('3/especial', '3/Especial')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='registroproducao',
            constraint=models.UniqueConstraint(fields=('linha', 'data', 'turno'), name='uniq_linha_data_turno'),
        ),
    ]
