# Generated by Django 5.2.3 on 2025-09-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0007_alter_registroproducao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoLinhaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnos_permitidos', models.CharField(help_text='Valores separados por vírgula. Ex.: "1/especial,2/especial"', max_length=200)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_usuarios', to='sgpi.linhaproducao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_linha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de linha por usuário',
                'verbose_name_plural': 'Permissões de linha por usuário',
                'unique_together': {('usuario', 'linha')},
            },
        ),
    ]
