# Generated by Django 5.2.3 on 2025-09-24 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgpi', '0008_permissaolinhausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoSetorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_setor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de setor por usuário',
                'verbose_name_plural': 'Permissões de setor por usuário',
                'unique_together': {('usuario', 'setor')},
            },
        ),
        migrations.DeleteModel(
            name='PermissaoLinhaUsuario',
        ),
    ]
